apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: michael-test
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: michael-test-java-quarkus-sample
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: michael-test-java-quarkus-sample
  namespace: midawson
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: michael-test-java-quarkus-sample
status:
  configuration:
    generatedName: ""
