apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: michael-test-java-quarkus-sample
  namespace: midawson
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:034b7b00dd7692c664849226c7799730d617355d979d783daea73225370aaf23
        name: container-image
        resources: {}
status: {}
